### PR TITLE
chore: replace traverse with neotraverse

### PR DESCRIPTION
**Pull request by digiz3d**
NGL I made this PR just to try it out. Hope it helps

This replaces `traverse` dependency, which is bloated with lots of useless dependencies, [especially since the 0.6.9 version](https://github.com/loopbackio/loopback-datasource-juggler/pull/2224).
Only to support node 0.4 that nobody uses anymore.

You can find many information about it on Twitter/X. Here is an article from the replacement library author here https://puruvj.dev/blog/forking-and-fixing-traverse

## Checklist

- [x] [Sign off your commits](https://loopback.io/doc/en/contrib/code-contrib.html) with DCO (Developer Certificate of Origin)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by dhmlau** [comment]
@digiz3d, thanks for the PR. And thanks for including the blog post, it's an interesting read :) 
Could you please rebase your branch to resolve the merge conflicts?

**Comment by digiz3d** [comment]
> @digiz3d, thanks for the PR. And thanks for including the blog post, it's an interesting read :) Could you please rebase your branch to resolve the merge conflicts?

Glad you found it interesting! done

**Comment by achrinza** [comment]
Hi @digiz3d, thanks for the pull request! Just need to fix the merge conflict - Could you regenerate the lockfile with `npm i --package-lock-only`? Then we should be good to merge.

**Comment by digiz3d** [comment]
> npm i --package-lock-only

I've rebased the PR, lockfile should be up to date now 👍

**Comment by achrinza** [comment]
Thanks, it's been merged!

**Pull request merged**
